Repository TeamOwori/Owori-Server, pull requests merged in 2023-10, with the labels that each got.

#110 [DOCS] story, keyword, image, heart, comment API 명세서 업데이트
  src/docs/comment.adoc
  src/docs/heart.adoc
  src/docs/image.adoc
  src/docs/keyword.adoc
  src/docs/story.adoc
  src/test/java/com/owori/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/owori/domain/heart/controller/HeartControllerTest.java
  src/test/java/com/owori/domain/image/controller/ImageControllerTest.java
  src/test/java/com/owori/domain/keyword/controller/KeywordControllerTest.java
  src/test/java/com/owori/domain/story/controller/StoryControllerTest.java
Labels: docs

#111 10월 6일 배포
  .github/workflows/owori-cd.yml
  src/docs/comment.adoc
  src/docs/heart.adoc
  src/docs/image.adoc
  src/docs/keyword.adoc
  src/docs/member.adoc
  src/docs/story.adoc
  src/main/java/com/owori/config/security/SecurityConfig.java
  src/main/java/com/owori/domain/member/client/GoogleMemberClient.java
  src/main/java/com/owori/domain/member/controller/MemberController.java
  src/main/java/com/owori/domain/member/dto/client/GoogleMemberResponse.java
  src/main/java/com/owori/domain/member/dto/request/MemberGoogleRequest.java
  src/main/java/com/owori/domain/member/entity/AuthProvider.java
  src/main/java/com/owori/domain/member/service/MemberService.java
  src/main/java/com/owori/domain/story/controller/StoryController.java
  src/main/java/com/owori/domain/story/dto/response/FindAllStoryGroupResponse.java
  src/main/java/com/owori/domain/story/dto/response/StoryPagingResponse.java
  src/main/java/com/owori/domain/story/repository/StoryRepositoryCustom.java
  src/main/java/com/owori/domain/story/repository/StoryRepositoryCustomImpl.java
  src/main/java/com/owori/domain/story/service/StoryService.java
  src/test/java/com/owori/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/owori/domain/heart/controller/HeartControllerTest.java
  src/test/java/com/owori/domain/image/controller/ImageControllerTest.java
  src/test/java/com/owori/domain/keyword/controller/KeywordControllerTest.java
  src/test/java/com/owori/domain/keyword/service/KeywordServiceTest.java
  src/test/java/com/owori/domain/member/controller/MemberControllerTest.java
  src/test/java/com/owori/domain/story/controller/StoryControllerTest.java
  src/test/java/com/owori/domain/story/service/StoryServiceTest.java
Labels: 배포

#115 [CHORE] 서버 모니터링 시스템 구축
  build.gradle
  src/main/java/com/owori/config/security/SecurityConfig.java
  src/main/resources/application-prod.yml
Labels: chore

#113 [FIX] Google 로그인 로직 수정
  build.gradle
  src/main/java/com/owori/domain/member/client/GoogleMemberClient.java
  src/main/java/com/owori/domain/member/exception/InvalidTokenException.java
Labels: fix

#116 10월 11일 배포
  build.gradle
  src/main/java/com/owori/config/security/SecurityConfig.java
  src/main/java/com/owori/domain/member/client/GoogleMemberClient.java
  src/main/java/com/owori/domain/member/exception/InvalidTokenException.java
  src/main/resources/application-prod.yml
Labels: 배포

#117 [FIX] actuator 접근 role 수정
  src/main/java/com/owori/config/security/SecurityConfig.java
Labels: fix

#119 배포
  src/main/java/com/owori/domain/member/entity/Member.java
  src/main/java/com/owori/domain/member/entity/Role.java
Labels: fix, 배포

#121 [FEAT] iOS 구글 로그인 관리
  src/main/java/com/owori/domain/member/client/GoogleMemberClient.java
  src/main/java/com/owori/domain/member/controller/MemberController.java
Labels: feat

#122 10월 18일 배포
  src/main/java/com/owori/domain/member/client/GoogleMemberClient.java
  src/main/java/com/owori/domain/member/controller/MemberController.java
Labels: 배포
