Repository TeamOwori/Owori-Server, pull requests merged in 2023-08, with the labels that each got.

#94 [REFACTOR] cleanup code and fix logic
  build.gradle
  src/main/java/com/owori/aspect/LogIntroduction.java
  src/main/java/com/owori/aspect/Logger.java
  src/main/java/com/owori/config/querydsl/QueryDslConfig.java
  src/main/java/com/owori/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/owori/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/owori/domain/comment/controller/CommentController.java
  src/main/java/com/owori/domain/comment/entity/Comment.java
  src/main/java/com/owori/domain/comment/entity/TimesAgo.java
  src/main/java/com/owori/domain/comment/mapper/CommentMapper.java
  src/main/java/com/owori/domain/comment/repository/CommentRepositoryCustomImpl.java
  src/main/java/com/owori/domain/comment/service/CommentService.java
  src/main/java/com/owori/domain/family/controller/FamilyController.java
  src/main/java/com/owori/domain/family/service/FamilyService.java
  src/main/java/com/owori/domain/heart/controller/HeartController.java
  src/main/java/com/owori/domain/heart/mapper/HeartMapper.java
  src/main/java/com/owori/domain/heart/service/HeartService.java
  src/main/java/com/owori/domain/image/controller/ImageController.java
  src/main/java/com/owori/domain/image/entity/Image.java
  src/main/java/com/owori/domain/image/exception/ImageLimitExceededException.java
  src/main/java/com/owori/domain/image/mapper/ImageMapper.java
  src/main/java/com/owori/domain/image/service/ImageService.java
  src/main/java/com/owori/domain/keyword/controller/KeywordController.java
  src/main/java/com/owori/domain/keyword/entity/Keyword.java
  src/main/java/com/owori/domain/keyword/repository/KeywordRepository.java
  src/main/java/com/owori/domain/keyword/service/KeywordService.java
  src/main/java/com/owori/domain/member/controller/AuthController.java
  src/main/java/com/owori/domain/member/controller/MemberController.java
  src/main/java/com/owori/domain/member/entity/Color.java
  src/main/java/com/owori/domain/member/entity/Member.java
  src/main/java/com/owori/domain/member/entity/OAuth2Info.java
  src/main/java/com/owori/domain/member/service/AuthService.java
  src/main/java/com/owori/domain/member/service/MemberService.java
  src/main/java/com/owori/domain/saying/controller/SayingController.java
  src/main/java/com/owori/domain/saying/repository/JpaSayingRepository.java
  src/main/java/com/owori/domain/saying/service/SayingService.java
  src/main/java/com/owori/domain/schedule/controller/ScheduleController.java
  src/main/java/com/owori/domain/schedule/entity/Schedule.java
  src/main/java/com/owori/domain/schedule/mapper/ScheduleMapper.java
  src/main/java/com/owori/domain/schedule/service/ScheduleService.java
  src/main/java/com/owori/domain/story/controller/StoryController.java
  src/main/java/com/owori/domain/story/entity/Story.java
  src/main/java/com/owori/domain/story/mapper/StoryMapper.java
  src/main/java/com/owori/domain/story/repository/StoryOrderConverter.java
  src/main/java/com/owori/domain/story/repository/StoryRepositoryCustomImpl.java
  src/main/java/com/owori/domain/story/service/FacadeService.java
  src/main/java/com/owori/domain/story/service/StoryService.java
  src/main/java/com/owori/domain/test/TestController.java
  src/main/java/com/owori/domain/test/TestService.java
  src/main/java/com/owori/global/advice/GlobalErrorAdvice.java
  src/main/java/com/owori/global/converter/OrderConverter.java
  src/main/java/com/owori/global/exception/NoAuthorityException.java
  src/main/java/com/owori/utils/S3ImageComponent.java
Labels: cleanup

#96 [REFACTOR] story DTO field명 변경 및 추가
  src/main/java/com/owori/domain/family/controller/FamilyController.java
  src/main/java/com/owori/domain/family/dto/response/FamilyImageResponse.java
  src/main/java/com/owori/domain/family/service/FamilyService.java
  src/main/java/com/owori/domain/image/controller/ImageController.java
  src/main/java/com/owori/domain/image/dto/response/ImagesStoryResponse.java
  src/main/java/com/owori/domain/image/entity/Image.java
  src/main/java/com/owori/domain/image/repository/ImageRepository.java
  src/main/java/com/owori/domain/image/repository/JpaImageRepository.java
  src/main/java/com/owori/domain/image/service/ImageService.java
  src/main/java/com/owori/domain/member/controller/MemberController.java
  src/main/java/com/owori/domain/member/dto/response/MemberImageResponse.java
  src/main/java/com/owori/domain/member/service/MemberService.java
  src/main/java/com/owori/domain/story/dto/request/PostStoryRequest.java
  src/main/java/com/owori/domain/story/dto/request/UpdateStoryRequest.java
  src/main/java/com/owori/domain/story/dto/response/FindAllStoryResponse.java
  src/main/java/com/owori/domain/story/dto/response/FindStoryResponse.java
  src/main/java/com/owori/domain/story/mapper/StoryMapper.java
  src/main/java/com/owori/domain/story/service/StoryService.java
  src/test/java/com/owori/domain/family/controller/FamilyControllerTest.java
  src/test/java/com/owori/domain/image/controller/ImageControllerTest.java
  src/test/java/com/owori/domain/member/controller/MemberControllerTest.java
  src/test/java/com/owori/domain/story/controller/StoryControllerTest.java
  src/test/java/com/owori/domain/story/service/StoryServiceTest.java
Labels: refactoring

#100 [FIX] 스토리 관련 오류 해결
  nginx/nginx.conf
  src/main/java/com/owori/domain/member/entity/EmotionalBadge.java
  src/main/java/com/owori/domain/story/dto/response/FindAllStoryResponse.java
  src/main/java/com/owori/domain/story/entity/Story.java
  src/main/java/com/owori/domain/story/mapper/StoryMapper.java
  src/main/java/com/owori/domain/story/repository/StoryRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/test/java/com/owori/domain/story/controller/StoryControllerTest.java
Labels: fix
