Repository TeamOwori/Owori-Server, pull requests merged in 2023-09, with the labels that each got.

#103 [CHORE] 데이터베이스 변경
  docker-compose.prod.yml
  src/main/resources/application-prod.yml
Labels: chore

#109 [FEAT] Google 로그인 API 구현
  src/docs/member.adoc
  src/main/java/com/owori/config/security/SecurityConfig.java
  src/main/java/com/owori/domain/member/client/GoogleMemberClient.java
  src/main/java/com/owori/domain/member/controller/MemberController.java
  src/main/java/com/owori/domain/member/dto/client/GoogleMemberResponse.java
  src/main/java/com/owori/domain/member/dto/request/MemberGoogleRequest.java
  src/main/java/com/owori/domain/member/entity/AuthProvider.java
  src/main/java/com/owori/domain/member/service/MemberService.java
  src/test/java/com/owori/domain/member/controller/MemberControllerTest.java
Labels: feat

#106 [REFACTOR] 무한 스크롤 구현 방식 수정
  src/main/java/com/owori/domain/story/controller/StoryController.java
  src/main/java/com/owori/domain/story/dto/response/FindAllStoryGroupResponse.java
  src/main/java/com/owori/domain/story/dto/response/StoryPagingResponse.java
  src/main/java/com/owori/domain/story/repository/StoryRepositoryCustom.java
  src/main/java/com/owori/domain/story/repository/StoryRepositoryCustomImpl.java
  src/main/java/com/owori/domain/story/service/StoryService.java
  src/test/java/com/owori/domain/keyword/service/KeywordServiceTest.java
  src/test/java/com/owori/domain/story/controller/StoryControllerTest.java
  src/test/java/com/owori/domain/story/service/StoryServiceTest.java
Labels: refactoring
