Repository TeamOwori/Owori-Server, pull requests merged in 2023-07, with the labels that each got.

#2 [CHORE] Api Docs 세팅 및 BaseTime 세팅
  .github/workflows/owori-ci.yml
  build.gradle
  src/docs/auth.adoc
  src/docs/index.adoc
  src/main/java/com/owori/OworiApplication.java
  src/main/java/com/owori/config/security/jwt/JwtToken.java
  src/main/java/com/owori/domain/member/controller/AuthController.java
  src/main/java/com/owori/domain/member/controller/MemberController.java
  src/main/java/com/owori/domain/member/entity/AuthProvider.java
  src/main/java/com/owori/domain/member/entity/Color.java
  src/main/java/com/owori/domain/member/entity/Member.java
  src/main/java/com/owori/domain/member/entity/Role.java
  src/main/java/com/owori/domain/member/repository/JpaMemberRepository.java
  src/main/java/com/owori/domain/member/repository/MemberRepository.java
  src/main/java/com/owori/domain/member/service/AuthService.java
  src/main/java/com/owori/domain/member/service/MemberService.java
  src/main/java/com/owori/global/audit/AuditListener.java
  src/main/java/com/owori/global/audit/Auditable.java
  src/main/java/com/owori/global/audit/BaseTime.java
  src/main/java/com/owori/global/audit/SoftDelete.java
  src/main/java/com/owori/global/exception/EntityNotFoundException.java
  src/main/java/com/owori/global/service/EntityLoader.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
  src/test/java/com/owori/OworiApplicationTests.java
  src/test/java/com/owori/domain/member/controller/AuthControllerTest.java
  src/test/java/com/owori/support/docs/ApiDocsUtils.java
  src/test/java/com/owori/support/docs/RestDocsConfig.java
  src/test/java/com/owori/support/docs/RestDocsTest.java
Labels: chore

#4 [FEAT] security 설정 및 kakao 소셜 로그인
  build.gradle
  src/main/java/com/owori/config/security/SecurityConfig.java
  src/main/java/com/owori/config/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/owori/config/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/owori/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/owori/config/security/jwt/JwtKeyConfig.java
  src/main/java/com/owori/config/security/jwt/JwtSetupService.java
  src/main/java/com/owori/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/owori/config/security/jwt/JwtValidator.java
  src/main/java/com/owori/config/security/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/owori/config/security/oauth/OAuth2Request.java
  src/main/java/com/owori/config/security/oauth/OAuth2UserServiceImpl.java
  src/main/java/com/owori/config/security/oauth/UserPrinciple.java
  src/main/java/com/owori/config/security/oauth/UserPrincipleMapper.java
  src/main/java/com/owori/config/security/oauth/attributemapper/AppleAttributeMapper.java
  src/main/java/com/owori/config/security/oauth/attributemapper/AttributeMappable.java
  src/main/java/com/owori/config/security/oauth/attributemapper/AttributeMapper.java
  src/main/java/com/owori/config/security/oauth/attributemapper/AttributeMapperFactory.java
  src/main/java/com/owori/config/security/oauth/attributemapper/KakaoAttributeMapper.java
  src/main/java/com/owori/domain/member/entity/Member.java
  src/main/java/com/owori/domain/member/entity/OAuth2Info.java
  src/main/java/com/owori/domain/member/exception/JwtProcessingException.java
  src/main/java/com/owori/domain/member/repository/JpaMemberRepository.java
  src/main/java/com/owori/domain/member/repository/MemberRepository.java
  src/main/java/com/owori/domain/member/service/AuthService.java
  src/main/java/com/owori/domain/member/service/MemberService.java
  src/main/java/com/owori/global/audit/AuditListener.java
  src/main/java/com/owori/global/audit/Auditable.java
  src/main/java/com/owori/global/audit/SoftDelete.java
Labels: feat

#8 [CHORE] 가족 생성 API와 member 가족에 추가 API에 대한 API docs
  build.gradle
  src/docs/family.adoc
  src/docs/index.adoc
  src/main/java/com/owori/config/security/SecurityConfig.java
  src/main/java/com/owori/domain/family/controller/FamilyController.java
  src/main/java/com/owori/domain/family/dto/request/AddMemberRequest.java
  src/main/java/com/owori/domain/family/dto/request/FamilyRequest.java
  src/main/java/com/owori/domain/family/dto/response/InviteCodeResponse.java
  src/main/java/com/owori/domain/family/entity/Family.java
  src/main/java/com/owori/domain/family/repository/FamilyRepository.java
  src/main/java/com/owori/domain/family/repository/JpaFamilyRepository.java
  src/main/java/com/owori/domain/family/service/FamilyService.java
  src/test/java/com/owori/domain/family/controller/FamilyControllerTest.java
  src/test/java/com/owori/domain/member/controller/AuthControllerTest.java
  src/test/java/com/owori/support/docs/RestDocsTest.java
Labels: chore

#11 [CHORE] 이야기 - API dosc 작업
  src/docs/index.adoc
  src/docs/story.adoc
  src/main/java/com/owori/domain/image/entity/Image.java
  src/main/java/com/owori/domain/story/controller/StoryController.java
  src/main/java/com/owori/domain/story/dto/request/AddStoryRequest.java
  src/main/java/com/owori/domain/story/dto/response/CommentResponse.java
  src/main/java/com/owori/domain/story/dto/response/FindAlbumStoryResponse.java
  src/main/java/com/owori/domain/story/dto/response/FindListStoryResponse.java
  src/main/java/com/owori/domain/story/dto/response/FindStoryResponse.java
  src/main/java/com/owori/domain/story/entity/Story.java
  src/main/java/com/owori/domain/story/repository/JpaStoryRepository.java
  src/main/java/com/owori/domain/story/repository/StoryRepository.java
  src/main/java/com/owori/domain/story/service/StoryService.java
  src/main/java/com/owori/global/dto/IdResponse.java
  src/test/java/com/owori/domain/story/controller/StoryControllerTest.java
Labels: chore

#15 [FEAT] 소셜 로그인 api 수정 및 추가
  src/docs/index.adoc
  src/docs/member.adoc
  src/main/java/com/owori/config/security/SecurityConfig.java
  src/main/java/com/owori/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/owori/config/security/jwt/JwtSetupService.java
  src/main/java/com/owori/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/owori/config/security/jwt/JwtValidator.java
  src/main/java/com/owori/config/security/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/owori/config/security/oauth/OAuth2UserServiceImpl.java
  src/main/java/com/owori/config/security/oauth/UserPrinciple.java
  src/main/java/com/owori/config/security/oauth/UserPrincipleMapper.java
  src/main/java/com/owori/config/security/oauth/attributemapper/AppleAttributeMapper.java
  src/main/java/com/owori/config/security/oauth/attributemapper/AttributeMappable.java
  src/main/java/com/owori/config/security/oauth/attributemapper/AttributeMapper.java
  src/main/java/com/owori/config/security/oauth/attributemapper/AttributeMapperFactory.java
  src/main/java/com/owori/config/security/oauth/attributemapper/KakaoAttributeMapper.java
  src/main/java/com/owori/domain/family/entity/Family.java
  src/main/java/com/owori/domain/family/entity/Invite.java
  src/main/java/com/owori/domain/member/controller/MemberController.java
  src/main/java/com/owori/domain/member/dto/request/MemberDetailsRequest.java
  src/main/java/com/owori/domain/member/dto/request/MemberRequest.java
  src/main/java/com/owori/domain/member/dto/response/MemberJwtResponse.java
  src/main/java/com/owori/domain/member/entity/Color.java
  src/main/java/com/owori/domain/member/entity/Member.java
  src/main/java/com/owori/domain/member/entity/OAuth2Info.java
  src/main/java/com/owori/domain/member/exception/NoSuchProfileImageException.java
  src/main/java/com/owori/domain/member/mapper/MemberMapper.java
  src/main/java/com/owori/domain/member/repository/JpaMemberRepository.java
  src/main/java/com/owori/domain/member/repository/MemberRepository.java
  src/main/java/com/owori/domain/member/service/AuthService.java
  src/main/java/com/owori/domain/member/service/MemberService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
  src/test/java/com/owori/OworiApplicationTests.java
  src/test/java/com/owori/domain/family/controller/FamilyControllerTest.java
  src/test/java/com/owori/domain/family/service/FamilyServiceTest.java
  src/test/java/com/owori/domain/member/controller/MemberControllerTest.java
  src/test/java/com/owori/domain/member/service/MemberServiceTest.java
  src/test/java/com/owori/domain/story/controller/StoryControllerTest.java
  src/test/java/com/owori/support/database/LoginTest.java
  src/test/java/com/owori/support/docs/RestDocsTest.java
Labels: feat

#16 [FIX] 이야기 작성 시 이야기 이미지 업로드 api 분리
  build.gradle
  src/docs/image.adoc
  src/docs/index.adoc
  src/main/java/com/owori/domain/image/controller/ImageController.java
  src/main/java/com/owori/domain/image/entity/Image.java
  src/main/java/com/owori/domain/image/exception/ImageLimitExceededException.java
  src/main/java/com/owori/domain/image/mapper/ImageMapper.java
  src/main/java/com/owori/domain/image/repository/ImageRepository.java
  src/main/java/com/owori/domain/image/repository/JpaImageRepository.java
  src/main/java/com/owori/domain/image/service/ImageService.java
  src/main/java/com/owori/domain/story/controller/StoryController.java
  src/main/java/com/owori/domain/story/dto/request/AddStoryRequest.java
  src/main/java/com/owori/domain/story/entity/Story.java
  src/main/java/com/owori/domain/story/mapper/StoryMapper.java
  src/main/java/com/owori/domain/story/repository/StoryRepository.java
  src/main/java/com/owori/domain/story/service/StoryService.java
  src/main/java/com/owori/utils/S3ImageComponent.java
  src/test/java/com/owori/domain/image/controller/ImageControllerTest.java
  src/test/java/com/owori/domain/story/controller/StoryControllerTest.java
Labels: fix

#17 [CHORE] 일정 - API docs 작업
  src/docs/index.adoc
  src/docs/index.html
  src/docs/schedule.adoc
  src/main/java/com/owori/domain/schedule/controller/ScheduleController.java
  src/main/java/com/owori/domain/schedule/dto/request/AddScheduleRequest.java
  src/main/java/com/owori/domain/schedule/dto/request/UpdateScheduleRequest.java
  src/main/java/com/owori/domain/schedule/dto/response/AddScheduleResponse.java
  src/main/java/com/owori/domain/schedule/dto/response/FindScheduleByMonthResponse.java
  src/main/java/com/owori/domain/schedule/dto/response/UpdateScheduleResponse.java
  src/main/java/com/owori/domain/schedule/entity/Alarm.java
  src/main/java/com/owori/domain/schedule/entity/Schedule.java
  src/main/java/com/owori/domain/schedule/entity/ScheduleType.java
  src/main/java/com/owori/domain/schedule/repository/JpaScheduleRepository.java
  src/main/java/com/owori/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/owori/domain/schedule/service/ScheduleService.java
  src/test/java/com/owori/domain/schedule/controller/ScheduleControllerTest.java
Labels: chore

#20 [FEAT] s3 프로필 이미지 api 연결 및 controller advice와 logging 구현
  src/docs/index.html
  src/main/java/com/owori/aspect/LogIntroduction.java
  src/main/java/com/owori/domain/family/controller/advice/FamilyErrorAdvice.java
  src/main/java/com/owori/domain/family/exception/InviteCodeDuplicateException.java
  src/main/java/com/owori/domain/member/controller/MemberController.java
  src/main/java/com/owori/domain/member/controller/advice/MemberErrorAdvice.java
  src/main/java/com/owori/domain/member/exception/NoSuchProfileImageException.java
  src/main/java/com/owori/domain/member/service/MemberService.java
  src/main/java/com/owori/global/advice/ErrorResponse.java
  src/main/java/com/owori/global/advice/GlobalErrorAdvice.java
  src/test/java/com/owori/domain/member/controller/MemberControllerTest.java
  src/test/java/com/owori/domain/schedule/controller/ScheduleControllerTest.java
Labels: feat

#21 [FEAT] 이야기 앨범형 조회(최신순/날짜순) API 추가
  build.gradle
  src/docs/index.html
  src/docs/story.adoc
  src/main/java/com/owori/config/security/querydsl/QueryDslConfig.java
  src/main/java/com/owori/domain/image/entity/Image.java
  src/main/java/com/owori/domain/image/service/ImageService.java
  src/main/java/com/owori/domain/story/controller/StoryController.java
  src/main/java/com/owori/domain/story/dto/collection/StoryAlbumGroup.java
  src/main/java/com/owori/domain/story/dto/collection/StoryGroupByYearMonth.java
  src/main/java/com/owori/domain/story/dto/response/FindAlbumStoryByMonthResponse.java
  src/main/java/com/owori/domain/story/dto/response/FindAlbumStoryGroupResponse.java
  src/main/java/com/owori/domain/story/dto/response/FindAlbumStoryResponse.java
  src/main/java/com/owori/domain/story/dto/response/FindListStoryGroupResponse.java
  src/main/java/com/owori/domain/story/dto/response/FindListStoryResponse.java
  src/main/java/com/owori/domain/story/dto/response/FindStoryResponse.java
  src/main/java/com/owori/domain/story/entity/Story.java
  src/main/java/com/owori/domain/story/exception/StoryOrderException.java
  src/main/java/com/owori/domain/story/repository/JpaStoryRepository.java
  src/main/java/com/owori/domain/story/repository/StoryOrderConverter.java
  src/main/java/com/owori/domain/story/repository/StoryRepository.java
  src/main/java/com/owori/domain/story/repository/StoryRepositoryCustom.java
  src/main/java/com/owori/domain/story/repository/StoryRepositoryCustomImpl.java
  src/main/java/com/owori/domain/story/service/StoryService.java
  src/main/java/com/owori/global/converter/OrderConverter.java
  src/test/java/com/owori/domain/story/controller/StoryControllerTest.java
  src/test/java/com/owori/domain/story/service/StoryServiceTest.java
Labels: feat

#24 [CHORE] member와 family request dto에 validation 추가
  src/main/java/com/owori/domain/family/controller/FamilyController.java
  src/main/java/com/owori/domain/member/controller/MemberController.java
  src/main/java/com/owori/domain/member/dto/request/MemberDetailsRequest.java
  src/main/java/com/owori/domain/member/dto/request/MemberRequest.java
Labels: chore

#28 [CHORE] member profile 업데이트, 회원 탈퇴 및 family name 업데이트, Jackson Config
  src/docs/family.adoc
  src/docs/member.adoc
  src/main/java/com/owori/config/mapper/LocalDateDeserializer.java
  src/main/java/com/owori/config/mapper/LocalDateSerializer.java
  src/main/java/com/owori/config/mapper/LocalDateTimeDeserializer.java
  src/main/java/com/owori/config/mapper/LocalDateTimeSerializer.java
  src/main/java/com/owori/config/mapper/ObjectMapperConfig.java
  src/main/java/com/owori/domain/family/controller/FamilyController.java
  src/main/java/com/owori/domain/family/entity/Family.java
  src/main/java/com/owori/domain/family/service/FamilyService.java
  src/main/java/com/owori/domain/member/controller/MemberController.java
  src/main/java/com/owori/domain/member/dto/request/MemberProfileRequest.java
  src/main/java/com/owori/domain/member/entity/Member.java
  src/main/java/com/owori/domain/member/service/MemberService.java
  src/test/java/com/owori/domain/family/controller/FamilyControllerTest.java
  src/test/java/com/owori/domain/family/service/FamilyServiceTest.java
  src/test/java/com/owori/domain/member/controller/MemberControllerTest.java
  src/test/java/com/owori/domain/member/service/MemberServiceTest.java
Labels: feat, chore

#30 [CHORE] 서로에게 한마디 - API docs 작성
  src/docs/index.adoc
  src/docs/saying.adoc
  src/main/java/com/owori/domain/saying/controller/SayingController.java
  src/main/java/com/owori/domain/saying/dto/request/AddSayingRequest.java
  src/main/java/com/owori/domain/saying/dto/request/UpdateSayingRequest.java
  src/main/java/com/owori/domain/saying/dto/response/FindSayingByFamilyResponse.java
  src/main/java/com/owori/domain/saying/entity/Saying.java
  src/main/java/com/owori/domain/saying/entity/SayingTagMember.java
  src/main/java/com/owori/domain/saying/repository/JpaSayingRepository.java
  src/main/java/com/owori/domain/saying/repository/SayingRepository.java
  src/main/java/com/owori/domain/saying/service/SayingService.java
  src/test/java/com/owori/domain/saying/controller/SayingControllerTest.java
Labels: chore

#33 [FEAT] webclient 로그인 api 적용
  build.gradle
  src/main/java/com/owori/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/owori/domain/member/client/KakaoMemberClient.java
  src/main/java/com/owori/domain/member/controller/advice/MemberErrorAdvice.java
  src/main/java/com/owori/domain/member/dto/client/KakaoMemberResponse.java
  src/main/java/com/owori/domain/member/entity/OAuth2Info.java
  src/main/java/com/owori/domain/member/exception/WebClientException.java
  src/main/java/com/owori/domain/member/mapper/MemberMapper.java
  src/main/java/com/owori/domain/member/repository/JpaMemberRepository.java
  src/main/java/com/owori/domain/member/repository/MemberRepository.java
  src/main/java/com/owori/domain/member/service/AuthService.java
  src/main/java/com/owori/domain/member/service/MemberService.java
Labels: feat

#35 [FEAT] 가족 사진 저장 api 및 api docs
  src/docs/family.adoc
  src/main/java/com/owori/domain/family/controller/FamilyController.java
  src/main/java/com/owori/domain/family/entity/Family.java
  src/main/java/com/owori/domain/family/service/FamilyService.java
  src/main/java/com/owori/domain/member/controller/MemberController.java
  src/main/java/com/owori/domain/member/service/MemberService.java
  src/main/java/com/owori/global/dto/ImageResponse.java
  src/test/java/com/owori/domain/family/controller/FamilyControllerTest.java
  src/test/java/com/owori/domain/member/controller/MemberControllerTest.java
Labels: feat

#39 [REFACTOR] 이야기 전체 조회 API로 통합
  src/docs/story.adoc
  src/main/java/com/owori/domain/comment/dto/request/AddCommentRequest.java
  src/main/java/com/owori/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/owori/domain/heart/controller/HeartController.java
  src/main/java/com/owori/domain/heart/dto/HeartStatusResponse.java
  src/main/java/com/owori/domain/heart/service/HeartService.java
  src/main/java/com/owori/domain/story/controller/StoryController.java
  src/main/java/com/owori/domain/story/dto/collection/StoryAlbumGroup.java
  src/main/java/com/owori/domain/story/dto/collection/StoryGroupByYearMonth.java
  src/main/java/com/owori/domain/story/dto/request/AddStoryRequest.java
  src/main/java/com/owori/domain/story/dto/response/FindAlbumStoryByMonthResponse.java
  src/main/java/com/owori/domain/story/dto/response/FindAlbumStoryGroupResponse.java
  src/main/java/com/owori/domain/story/dto/response/FindAlbumStoryResponse.java
  src/main/java/com/owori/domain/story/dto/response/FindAllStoryGroupResponse.java
  src/main/java/com/owori/domain/story/dto/response/FindAllStoryResponse.java
  src/main/java/com/owori/domain/story/dto/response/FindListStoryResponse.java
  src/main/java/com/owori/domain/story/dto/response/FindStoryResponse.java
  src/main/java/com/owori/domain/story/entity/Story.java
  src/main/java/com/owori/domain/story/exception/StoryOrderException.java
  src/main/java/com/owori/domain/story/mapper/StoryMapper.java
  src/main/java/com/owori/domain/story/repository/StoryOrderConverter.java
  src/main/java/com/owori/domain/story/repository/StoryRepository.java
  src/main/java/com/owori/domain/story/repository/StoryRepositoryCustom.java
  src/main/java/com/owori/domain/story/repository/StoryRepositoryCustomImpl.java
  src/main/java/com/owori/domain/story/service/StoryService.java
  src/test/java/com/owori/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/owori/domain/heart/controller/HeartControllerTest.java
  src/test/java/com/owori/domain/heart/service/HeartServiceTest.java
  src/test/java/com/owori/domain/story/controller/StoryControllerTest.java
  src/test/java/com/owori/domain/story/service/StoryServiceTest.java
Labels: refactoring

#43 [FEAT] update emotional badge api
  src/docs/member.adoc
  src/main/java/com/owori/domain/member/controller/MemberController.java
  src/main/java/com/owori/domain/member/dto/request/EmotionalBadgeRequest.java
  src/main/java/com/owori/domain/member/entity/EmotionalBadge.java
  src/main/java/com/owori/domain/member/entity/Member.java
  src/main/java/com/owori/domain/member/service/MemberService.java
  src/test/java/com/owori/domain/member/controller/MemberControllerTest.java
  src/test/java/com/owori/domain/member/service/MemberServiceTest.java
Labels: feat

#41 [FEAT] apple login api 처리
  src/main/java/com/owori/domain/member/service/MemberService.java
Labels: feat

#44 [FEAT] 일정 생성/수정/월별 조회 API
  src/main/java/com/owori/domain/schedule/controller/ScheduleController.java
  src/main/java/com/owori/domain/schedule/dto/request/AddScheduleRequest.java
  src/main/java/com/owori/domain/schedule/dto/request/UpdateScheduleRequest.java
  src/main/java/com/owori/domain/schedule/dto/response/AddScheduleResponse.java
  src/main/java/com/owori/domain/schedule/dto/response/FindScheduleByMonthResponse.java
  src/main/java/com/owori/domain/schedule/dto/response/UpdateScheduleResponse.java
  src/main/java/com/owori/domain/schedule/entity/Alarm.java
  src/main/java/com/owori/domain/schedule/entity/Schedule.java
  src/main/java/com/owori/domain/schedule/entity/ScheduleType.java
  src/main/java/com/owori/domain/schedule/exception/NoAuthorityUpdateException.java
  src/main/java/com/owori/domain/schedule/mapper/ScheduleMapper.java
  src/main/java/com/owori/domain/schedule/repository/JpaScheduleRepository.java
  src/main/java/com/owori/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/owori/domain/schedule/service/ScheduleService.java
  src/test/java/com/owori/domain/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/owori/domain/schedule/service/ScheduleServiceTest.java
Labels: feat

#50 [FEAT] 이야기 상세 조회 / 수정 / 삭제 API 추가
  src/docs/story.adoc
  src/main/java/com/owori/domain/comment/controller/CommentController.java
  src/main/java/com/owori/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/owori/domain/comment/entity/Comment.java
  src/main/java/com/owori/domain/comment/entity/TimesAgo.java
  src/main/java/com/owori/domain/comment/mapper/CommentMapper.java
  src/main/java/com/owori/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/owori/domain/comment/repository/CommentRepositoryCustomImpl.java
  src/main/java/com/owori/domain/comment/service/CommentService.java
  src/main/java/com/owori/domain/heart/controller/HeartController.java
  src/main/java/com/owori/domain/heart/repository/HeartRepository.java
  src/main/java/com/owori/domain/heart/service/HeartService.java
  src/main/java/com/owori/domain/image/repository/ImageRepository.java
  src/main/java/com/owori/domain/image/service/ImageService.java
  src/main/java/com/owori/domain/story/controller/StoryController.java
  src/main/java/com/owori/domain/story/dto/request/PostStoryRequest.java
  src/main/java/com/owori/domain/story/dto/response/FindStoryResponse.java
  src/main/java/com/owori/domain/story/entity/Story.java
  src/main/java/com/owori/domain/story/exception/InvalidUserException.java
  src/main/java/com/owori/domain/story/mapper/StoryMapper.java
  src/main/java/com/owori/domain/story/service/FacadeService.java
  src/main/java/com/owori/domain/story/service/StoryService.java
  src/test/java/com/owori/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/owori/domain/comment/service/CommentServiceTest.java
  src/test/java/com/owori/domain/heart/controller/HeartControllerTest.java
  src/test/java/com/owori/domain/heart/service/HeartServiceTest.java
  src/test/java/com/owori/domain/story/controller/StoryControllerTest.java
  src/test/java/com/owori/domain/story/service/StoryServiceTest.java
Labels: feat

#47 [CHORE] 일정 삭제 API Docs
  src/docs/schedule.adoc
  src/main/java/com/owori/domain/saying/entity/Saying.java
  src/main/java/com/owori/domain/saying/exception/NoAuthorityUpdateException.java
  src/main/java/com/owori/domain/saying/service/SayingService.java
  src/main/java/com/owori/domain/schedule/controller/ScheduleController.java
  src/main/java/com/owori/domain/schedule/exception/NoAuthorityUpdateException.java
  src/main/java/com/owori/domain/schedule/service/ScheduleService.java
  src/main/java/com/owori/global/advice/GlobalErrorAdvice.java
  src/main/java/com/owori/global/exception/NoAuthorityException.java
  src/test/java/com/owori/domain/saying/controller/SayingControllerTest.java
  src/test/java/com/owori/domain/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/owori/domain/schedule/service/ScheduleServiceTest.java
Labels: chore

#53 [FEAT] 이야기 검색 API, API Docs 추가
  src/docs/story.adoc
  src/main/java/com/owori/domain/comment/entity/TimesAgo.java
  src/main/java/com/owori/domain/story/controller/StoryController.java
  src/main/java/com/owori/domain/story/dto/request/SearchStoryRequest.java
  src/main/java/com/owori/domain/story/repository/StoryRepositoryCustom.java
  src/main/java/com/owori/domain/story/repository/StoryRepositoryCustomImpl.java
  src/main/java/com/owori/domain/story/service/StoryService.java
  src/test/java/com/owori/domain/comment/service/CommentServiceTest.java
  src/test/java/com/owori/domain/story/controller/StoryControllerTest.java
  src/test/java/com/owori/domain/story/service/StoryServiceTest.java
Labels: feat

#54 [FEAT] 유저가 좋아한 이야기 / 작성한 이야기 API, API Docs
  src/docs/story.adoc
  src/main/java/com/owori/domain/story/controller/StoryController.java
  src/main/java/com/owori/domain/story/mapper/StoryMapper.java
  src/main/java/com/owori/domain/story/repository/StoryRepositoryCustom.java
  src/main/java/com/owori/domain/story/repository/StoryRepositoryCustomImpl.java
  src/main/java/com/owori/domain/story/service/StoryService.java
  src/test/java/com/owori/domain/story/controller/StoryControllerTest.java
  src/test/java/com/owori/domain/story/service/StoryServiceTest.java
Labels: feat

#56 [CHORE] rename dto variable
  src/main/java/com/owori/domain/member/dto/request/MemberDetailsRequest.java
  src/main/java/com/owori/domain/member/service/MemberService.java
Labels: chore

#59 [FEAT] 메인 화면 조회 API
  src/docs/member.adoc
  src/main/java/com/owori/domain/member/controller/MemberController.java
  src/main/java/com/owori/domain/member/dto/response/MemberHomeResponse.java
  src/main/java/com/owori/domain/member/dto/response/MemberProfileResponse.java
  src/main/java/com/owori/domain/member/entity/Member.java
  src/main/java/com/owori/domain/member/mapper/MemberMapper.java
  src/main/java/com/owori/domain/member/service/MemberService.java
  src/main/java/com/owori/domain/saying/controller/SayingController.java
  src/main/java/com/owori/domain/saying/dto/response/SayingByFamilyResponse.java
  src/main/java/com/owori/domain/saying/entity/Saying.java
  src/main/java/com/owori/domain/saying/mapper/SayingMapper.java
  src/main/java/com/owori/domain/saying/service/SayingService.java
  src/main/java/com/owori/domain/schedule/controller/ScheduleController.java
  src/main/java/com/owori/domain/schedule/dto/response/ScheduleByMonthResponse.java
  src/main/java/com/owori/domain/schedule/dto/response/ScheduleDDayResponse.java
  src/main/java/com/owori/domain/schedule/mapper/ScheduleMapper.java
  src/main/java/com/owori/domain/schedule/service/ScheduleService.java
  src/test/java/com/owori/domain/member/controller/MemberControllerTest.java
  src/test/java/com/owori/domain/member/service/MemberServiceTest.java
  src/test/java/com/owori/domain/saying/controller/SayingControllerTest.java
  src/test/java/com/owori/domain/saying/service/SayingServiceTest.java
  src/test/java/com/owori/domain/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/owori/domain/schedule/service/ScheduleServiceTest.java
Labels: feat

#61 [FEAT] NginX 추가
  docker-compose.yml
  nginx/Dockerfile
  nginx/nginx.conf
Labels: feat

#65 [FIX] DTO 변수명 통일
  src/main/java/com/owori/domain/member/dto/response/MemberHomeResponse.java
  src/main/java/com/owori/domain/member/mapper/MemberMapper.java
  src/main/java/com/owori/domain/saying/service/SayingService.java
  src/main/java/com/owori/domain/schedule/dto/request/AddScheduleRequest.java
  src/main/java/com/owori/domain/schedule/dto/request/UpdateScheduleRequest.java
  src/main/java/com/owori/domain/schedule/dto/response/ScheduleByMonthResponse.java
  src/main/java/com/owori/domain/schedule/dto/response/ScheduleDDayResponse.java
  src/main/java/com/owori/domain/schedule/entity/Alarm.java
  src/main/java/com/owori/domain/schedule/entity/ScheduleType.java
  src/main/java/com/owori/domain/schedule/mapper/ScheduleMapper.java
  src/main/java/com/owori/domain/schedule/service/ScheduleService.java
  src/test/java/com/owori/domain/member/controller/MemberControllerTest.java
  src/test/java/com/owori/domain/member/service/MemberServiceTest.java
Labels: fix

#69 [CHORE] Lob 추가로 refresh token 데이터 타입 변경
  src/main/java/com/owori/config/querydsl/QueryDslConfig.java
  src/main/java/com/owori/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/owori/domain/member/entity/OAuth2Info.java
  src/main/java/com/owori/domain/member/service/AuthService.java
  src/main/java/com/owori/domain/member/service/MemberService.java
Labels: feat

#71 [FIX] 좋아요 재생성 오류 해결
  src/main/java/com/owori/domain/comment/service/CommentService.java
  src/main/java/com/owori/domain/heart/service/HeartService.java
  src/main/java/com/owori/domain/image/service/ImageService.java
  src/main/java/com/owori/domain/keyword/service/KeywordService.java
  src/main/java/com/owori/domain/story/service/FacadeService.java
  src/main/java/com/owori/domain/story/service/StoryService.java
Labels: fix

#73 [FEAT] 최근 검색어 API Docs 추가
  src/docs/index.adoc
  src/docs/keyword.adoc
Labels: feat

#75 [CHORE] 배포 세팅
  .github/workflows/owori-cd.yml
  build.gradle
  docker-compose.prod.yml
  src/main/java/com/owori/domain/member/service/MemberService.java
  src/main/resources/application-prod.yml
Labels: chore

#76 [REFACTOR] story 관련 validation 추가
  src/main/java/com/owori/domain/comment/service/CommentService.java
  src/main/java/com/owori/domain/keyword/service/KeywordService.java
  src/main/java/com/owori/domain/story/controller/StoryController.java
  src/main/java/com/owori/domain/story/dto/request/PostStoryRequest.java
  src/main/java/com/owori/domain/story/exception/InvalidUserException.java
  src/main/java/com/owori/domain/story/service/StoryService.java
  src/main/java/com/owori/global/advice/GlobalErrorAdvice.java
Labels: refactoring

#79 [TEST] 더미데이터 추가 API
  src/main/java/com/owori/config/security/SecurityConfig.java
  src/main/java/com/owori/domain/test/TestController.java
  src/main/java/com/owori/domain/test/TestService.java
Labels: test

#82 [FIX] basetime 설정 수정
  src/main/java/com/owori/global/audit/AuditListener.java
Labels: bug, fix

#83 [FEAT] 멤버의 수정 가능 색상 조회 api, api docs
  src/docs/member.adoc
  src/main/java/com/owori/domain/member/controller/MemberController.java
  src/main/java/com/owori/domain/member/dto/response/MemberColorResponse.java
  src/main/java/com/owori/domain/member/entity/Color.java
  src/main/java/com/owori/domain/member/mapper/MemberMapper.java
  src/main/java/com/owori/domain/member/service/MemberService.java
  src/test/java/com/owori/domain/member/controller/MemberControllerTest.java
  src/test/java/com/owori/domain/member/service/MemberServiceTest.java
Labels: feat

#85 [FEAT] 마이페이지 유저 프로필 조회 API, API Docs
  src/docs/member.adoc
  src/main/java/com/owori/domain/keyword/controller/KeywordController.java
  src/main/java/com/owori/domain/keyword/dto/response/FindKeywordsResponse.java
  src/main/java/com/owori/domain/keyword/service/KeywordService.java
  src/main/java/com/owori/domain/member/controller/MemberController.java
  src/main/java/com/owori/domain/member/dto/response/MemberProfileResponse.java
  src/main/java/com/owori/domain/member/dto/response/MyPageProfileResponse.java
  src/main/java/com/owori/domain/member/mapper/MemberMapper.java
  src/main/java/com/owori/domain/member/service/MemberService.java
  src/test/java/com/owori/domain/keyword/controller/KeywordControllerTest.java
  src/test/java/com/owori/domain/keyword/service/KeywordServiceTest.java
  src/test/java/com/owori/domain/member/controller/MemberControllerTest.java
  src/test/java/com/owori/domain/member/service/MemberServiceTest.java
Labels: feat

#87 [FEAT] 가족 초대 코드 재생성 api, api docs
  src/docs/family.adoc
  src/docs/member.adoc
  src/main/java/com/owori/aspect/LogIntroduction.java
  src/main/java/com/owori/aspect/Logger.java
  src/main/java/com/owori/domain/family/controller/FamilyController.java
  src/main/java/com/owori/domain/family/controller/advice/FamilyErrorAdvice.java
  src/main/java/com/owori/domain/family/entity/Family.java
  src/main/java/com/owori/domain/family/exception/InviteCodeExistException.java
  src/main/java/com/owori/domain/family/service/FamilyService.java
  src/test/java/com/owori/domain/family/controller/FamilyControllerTest.java
  src/test/java/com/owori/domain/family/service/FamilyServiceTest.java
Labels: feat

#88 [REFACTOR] 일정, 서로에게 한마디 관련 validation 추가 및 null 예외처리
  src/main/java/com/owori/domain/saying/controller/SayingController.java
  src/main/java/com/owori/domain/saying/dto/request/AddSayingRequest.java
  src/main/java/com/owori/domain/saying/dto/request/UpdateSayingRequest.java
  src/main/java/com/owori/domain/schedule/controller/ScheduleController.java
  src/main/java/com/owori/domain/schedule/dto/request/AddScheduleRequest.java
  src/main/java/com/owori/domain/schedule/dto/request/UpdateScheduleRequest.java
  src/main/java/com/owori/domain/schedule/dto/response/ScheduleDDayResponse.java
  src/main/java/com/owori/domain/schedule/mapper/ScheduleMapper.java
  src/main/resources/application-local.yml
Labels: refactoring

#92 [FIX] 테스트 코드, 예외처리 수정
  src/main/java/com/owori/domain/keyword/service/KeywordService.java
  src/main/java/com/owori/domain/story/entity/Story.java
  src/main/java/com/owori/domain/story/service/StoryService.java
  src/test/java/com/owori/domain/heart/service/HeartServiceTest.java
  src/test/java/com/owori/domain/story/service/StoryServiceTest.java
Labels: fix
